"use client";

import { type AuthUser } from "../../../lib/auth-api";
import { BadgeCheck, Check, ChevronRight, Coffee, CreditCard, Edit3, Ellipsis, Eye, LogOut, MessageSquareText, PackageCheck, Plus, Share2 } from "lucide-react";
import { userInitials } from "../model";
import { Button, IconButton, StatusPill, PageHeader, PanelTitle, Field, ToggleRow } from "../ui";

export function HistoryScreen({ notify }: { notify: (message: string) => void }) {
  return <><PageHeader title="Мои заказы" subtitle="История визитов, заказов и оплат." /><div className="history-list"><article className="panel active-order"><div className="order-venue"><span className="venue-mini" /><div><small>СЕГОДНЯ · В ЗАЛЕ</small><h3>North & Vine</h3><p>Заказ #1049 · Стол 08</p></div><StatusPill status="Готовится" /></div><div className="progress-track"><i className="done"><Check size={13} /></i><span /><i className="done"><Check size={13} /></i><span /><i className="current"><Coffee size={13} /></i><span /><i><PackageCheck size={13} /></i></div><div className="progress-labels"><span>Принят</span><span>Подтвержден</span><span>Готовится</span><span>Готов</span></div><footer><div><strong>€58.50</strong><span>3 позиции</span></div><Button kind="secondary" icon={Share2} onClick={() => notify("Ссылка на заказ скопирована")}>Поделиться</Button><Button icon={Eye}>Следить за заказом</Button></footer></article>{[["14 июля","North & Vine","€76.50","5 позиций"],["8 июля","Casa Forma","€41.20","3 позиции"],["28 июня","Mizu Table","€64.00","4 позиции"]].map((row,index) => <article className="panel past-order" key={row[0]}><span className={`past-thumb pos-${index}`} /><div><small>{row[0]} · ОПЛАЧЕН</small><h3>{row[1]}</h3><p>{row[3]} · Карта •••• 4242</p></div><strong>{row[2]}</strong><Button kind="quiet" icon={MessageSquareText} onClick={() => notify("Форма отзыва открыта")}>Оставить отзыв</Button><IconButton icon={ChevronRight} label="Подробнее" /></article>)}</div></>;
}

export function ProfileScreen({ user, notify, onLogout }: { user: AuthUser; notify: (message: string) => void; onLogout: () => void }) {
	return <><PageHeader title="Профиль" subtitle="Ваш аккаунт, предпочтения и способы оплаты." /><div className="profile-layout"><aside className="panel profile-card"><span className="profile-avatar">{userInitials(user)}</span><h2>{user.first_name} {user.last_name}</h2><p>Аккаунт Pocket</p><div><span><strong>12</strong><small>заказов</small></span><span><strong>4</strong><small>отзыва</small></span><span><strong>6</strong><small>мест</small></span></div><Button kind="quiet" icon={LogOut} onClick={onLogout}>Выйти</Button></aside><section className="panel settings-form"><PanelTitle title="Личные данные" action={<Button kind="secondary" icon={Edit3} onClick={() => notify("Профиль сохранен")}>Изменить</Button>} /><div className="form-grid"><Field label="Имя"><input defaultValue={user.first_name} /></Field><Field label="Фамилия"><input defaultValue={user.last_name} /></Field><Field label="E-mail"><input type="email" defaultValue={user.email} /></Field><Field label="Телефон"><input type="tel" defaultValue={user.phone ?? ""} placeholder="Добавить телефон" /></Field></div><hr /><PanelTitle title="Оплата" /><div className="saved-card"><span><CreditCard size={20} /></span><div><strong>Visa •••• 4242</strong><small>Срок действия 08/29</small></div><BadgeCheck size={18} /><IconButton icon={Ellipsis} label="Настройки карты" /></div><Button kind="quiet" icon={Plus}>Добавить способ оплаты</Button><hr /><PanelTitle title="Предпочтения" /><div className="setting-toggles"><ToggleRow title="Безлактозные блюда" text="Показывать подсказки в меню." checked /><ToggleRow title="Новости любимых мест" text="Редкие и полезные письма от заведений." /></div></section></div></>;
}


