"use client";

import { useState } from "react";
import { CalendarDays, Check, ChevronLeft, CreditCard, Heart, Minus, Plus, Search, Share2, ShieldCheck, ShoppingBag, Star, Trash2, WalletCards } from "lucide-react";
import { menuItems } from "../model";
import { money, Button, IconButton, FoodImage, EmptyIllustration, PageHeader, PanelTitle } from "../ui";

export function CustomerMenu({ cart, onAdd, onCart }: { cart: Record<number, number>; onAdd: (id: number) => void; onCart: () => void }) {
  const [category, setCategory] = useState("Все");
  const categories = ["Все", "Закуски", "Паста", "Основное", "Десерты", "Напитки"];
  const visible = category === "Все" ? menuItems : menuItems.filter((item) => item.category === category);
  return <><section className="restaurant-header"><div className="restaurant-cover" /><div className="restaurant-info"><div><p><span className="open-dot" />Открыто до 22:30</p><h1>North & Vine</h1><span><Star size={15} fill="currentColor" />4.8 · Современная европейская · €€</span></div><div><Button kind="secondary" icon={CalendarDays}>Забронировать</Button><IconButton icon={Share2} label="Поделиться" /><IconButton icon={Heart} label="В избранное" /></div></div></section><div className="menu-sticky"><div className="category-tabs">{categories.map((item) => <button key={item} className={category === item ? "active" : ""} onClick={() => setCategory(item)}>{item}</button>)}</div><IconButton icon={Search} label="Поиск по меню" /></div><section className="customer-menu-section"><PageHeader title={category === "Все" ? "Сегодня в меню" : category} subtitle="Готовим из сезонных продуктов. Сообщите нам об аллергиях." /><div className="food-grid">{visible.map((item) => <article className="food-card" key={item.id}><FoodImage item={item} /><button className="heart-float" title="В избранное"><Heart size={17} /></button>{item.popular && <span className="food-badge">Выбор гостей</span>}<div><small>{item.category}</small><h3>{item.name}</h3><p>{item.description}</p><footer><strong>{money(item.price)}</strong>{cart[item.id] ? <div className="qty-inline"><button onClick={() => onAdd(item.id)}><Plus size={15} /></button><span>{cart[item.id]}</span><Check size={15} /></div> : <IconButton icon={Plus} label="Добавить" onClick={() => onAdd(item.id)} />}</footer></div></article>)}</div></section>{Object.keys(cart).length > 0 && <button className="floating-cart" onClick={onCart}><span><ShoppingBag size={19} /><b>{Object.values(cart).reduce((a,b) => a+b,0)}</b></span><strong>Посмотреть заказ</strong><em>{money(menuItems.reduce((s,i) => s+i.price*(cart[i.id]||0),0))}</em></button>}</>;
}

export function Checkout({ cart, total, updateQty, onBack, onDone }: { cart: Record<number, number>; total: number; updateQty: (id: number, delta: number) => void; onBack: () => void; onDone: () => void }) {
  const [tip, setTip] = useState(10);
  const [method, setMethod] = useState("card");
  const tipValue = total * tip / 100;
  const selected = menuItems.filter((item) => cart[item.id]);
  return <><button className="back-link" onClick={onBack}><ChevronLeft size={17} />Вернуться в меню</button><PageHeader title="Ваш заказ" subtitle="North & Vine · Стол 08" /><div className="checkout-layout"><section className="checkout-main"><div className="panel checkout-items"><PanelTitle title={`Позиции · ${Object.values(cart).reduce((a,b)=>a+b,0)}`} />{selected.length ? selected.map((item) => <div className="checkout-item" key={item.id}><FoodImage item={item} /><div><strong>{item.name}</strong><small>Без изменений</small><button>Добавить комментарий</button></div><div className="qty-control"><IconButton icon={cart[item.id] === 1 ? Trash2 : Minus} label="Уменьшить" onClick={() => updateQty(item.id, -1)} /><span>{cart[item.id]}</span><IconButton icon={Plus} label="Увеличить" onClick={() => updateQty(item.id, 1)} /></div><b>{money(item.price * cart[item.id])}</b></div>) : <EmptyIllustration icon={ShoppingBag} title="Корзина пуста" text="Вернитесь в меню и выберите блюда." />}</div><div className="panel"><PanelTitle title="Чаевые команде" subtitle="100% чаевых получают сотрудники" /><div className="tip-options">{[0, 5, 10, 15].map((value) => <button className={tip === value ? "active" : ""} key={value} onClick={() => setTip(value)}>{value === 0 ? "Без чаевых" : `${value}%`}</button>)}<button className={tip === 20 ? "active" : ""} onClick={() => setTip(20)}>Другая сумма</button></div></div><div className="panel"><PanelTitle title="Способ оплаты" /><div className="payment-options"><button className={method === "card" ? "active" : ""} onClick={() => setMethod("card")}><CreditCard size={20} /><span><strong>Карта •••• 4242</strong><small>Основной способ</small></span><i /></button><button className={method === "apple" ? "active" : ""} onClick={() => setMethod("apple")}><WalletCards size={20} /><span><strong>Apple Pay</strong><small>Быстрая оплата</small></span><i /></button></div></div></section><aside className="panel order-summary"><PanelTitle title="Итого" /><dl><div><dt>Блюда</dt><dd>{money(total)}</dd></div><div><dt>Сервисный сбор</dt><dd>€0.00</dd></div><div><dt>Чаевые ({tip}%)</dt><dd>{money(tipValue)}</dd></div></dl><div className="summary-total"><span>К оплате</span><strong>{money(total + tipValue)}</strong></div><Button className="full pay-button" icon={ShieldCheck} disabled={!selected.length} onClick={onDone}>Оплатить {money(total + tipValue)}</Button><p className="secure-note"><ShieldCheck size={14} />Безопасная оплата через Stripe</p></aside></div></>;
}


