"use client";

import { useState } from "react";
import { Check, ChevronLeft, ChevronRight, MapPin, Table2, Utensils } from "lucide-react";
import { Button, PageHeader, Field } from "../ui";
import { tables } from "../floor-plan";

export function ReservationScreen({ onMenu, notify }: { onMenu: () => void; notify: (message: string) => void }) {
  const [step, setStep] = useState(1); const [table, setTable] = useState("08");
  return <><PageHeader title="Забронировать стол" subtitle="North & Vine · Štúrova 12" /><div className="reservation-layout"><section className="panel reservation-main"><div className="stepper"><span className={step >= 1 ? "active" : ""}><b>1</b>Когда</span><i /><span className={step >= 2 ? "active" : ""}><b>2</b>Стол</span><i /><span className={step >= 3 ? "active" : ""}><b>3</b>Детали</span></div>{step === 1 && <div className="reservation-step"><h2>Когда вас ждать?</h2><div className="date-strip">{[["Вс","19"],["Пн","20"],["Вт","21"],["Ср","22"],["Чт","23"]].map((d,i) => <button className={i===0 ? "active" : ""} key={d[1]}><small>{d[0]}</small><strong>{d[1]}</strong></button>)}</div><Field label="Количество гостей"><select defaultValue="4"><option>2</option><option>3</option><option>4</option><option>5</option><option>6</option></select></Field><div className="time-grid">{["18:00","18:30","19:00","19:30","20:00","20:30","21:00","21:30"].map((t,i) => <button className={i===3 ? "active" : ""} key={t}>{t}</button>)}</div></div>}{step === 2 && <div className="reservation-step"><h2>Выберите стол</h2><p>Можно выбрать конкретный свободный стол.</p><div className="mini-floor">{tables.map((t) => <button key={t.id} disabled={t.state === "busy"} className={`${t.id === table ? "active" : ""} ${t.state}`} onClick={() => setTable(t.id)}><Table2 size={18} /><strong>{t.id}</strong><small>{t.seats} места</small></button>)}</div></div>}{step === 3 && <div className="reservation-step"><h2>Последние детали</h2><div className="form-grid"><Field label="Имя"><input defaultValue="Денис" /></Field><Field label="Телефон"><input defaultValue="+421 900 123 456" /></Field><Field label="Комментарий" wide><textarea placeholder="Детский стул, аллергии или повод" /></Field></div><button className="preorder-callout" onClick={onMenu}><span><Utensils size={20} /></span><div><strong>Заказать блюда заранее</strong><p>Добавьте позиции, и мы начнем готовить к вашему приходу.</p></div><ChevronRight size={18} /></button></div>}<div className="reservation-actions">{step > 1 ? <Button kind="secondary" onClick={() => setStep(step-1)} icon={ChevronLeft}>Назад</Button> : <span />}{step < 3 ? <Button onClick={() => setStep(step+1)}>Продолжить <ChevronRight size={17} /></Button> : <Button icon={Check} onClick={() => notify(`Стол ${table} забронирован на 19:30`)}>Подтвердить бронь</Button>}</div></section><aside className="panel reservation-summary"><div className="reservation-photo" /><h3>North & Vine</h3><p><MapPin size={15} />Štúrova 12, Bratislava</p><dl><div><dt>Дата</dt><dd>19 июля</dd></div><div><dt>Время</dt><dd>19:30</dd></div><div><dt>Гости</dt><dd>4</dd></div><div><dt>Стол</dt><dd>{table}</dd></div></dl><small>Бесплатная отмена не позднее чем за 2 часа.</small></aside></div></>;
}


